# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.8
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: enalsy22@gmail.com
author_name: Abasiodiong Udofia
preset_name: starter
project_name: decent_pass-frontend

