# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.12
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: enalsy22@gmail.com
author_name: Abasiodiong Udofia
contract_name: decent_pass_smartcontract
deployment_language: python
preset_name: starter
project_name: decent_pass

